### ISSUE TITLE
Cannot read property 'clientWebpack' of undefined

### ISSUE THREAD

**Issue by CurryWurry** [sudheerj/generator-jhipster-primeng#67] opened 2019-01-30 12:36 UTC
When using `yo jhipster-primeng` on a new jhipster project, this exception is thrown after selecting the components to use

`events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'clientWebpack' of undefined
`
generator version : 2.2.0
jhipster version: 5.8.1
node version: 8.15.0
npm version: 6.4.1

This happens no matter what theme/component is selected

**Comment by bornf** [comment] 2019-01-30 15:25
npm: '6.7.0'

same error:

`events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'clientWebpack' of undefined
    at constructor.copyExternalAssetsInWebpack (/usr/local/lib/node_modules/generator-jhipster-primeng/node_modules/generator-jhipster/generators/generator-base.js:671:24)
    at constructor.writing (/usr/local/lib/node_modules/generator-jhipster-primeng/generators/app/index.js:224:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-primeng/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:418:27)
    at /usr/local/lib/node_modules/generator-jhipster-primeng/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster-primeng/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/local/lib/node_modules/generator-jhipster-primeng/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:419:13)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
`

**Comment by sudheerj** [comment] 2019-02-01 14:18
Thanks for reporting. Let me try to replicate the issue with latest JHipster version.

**Comment by sudheerj** [comment] 2019-02-02 16:19
When I tried to replicate the issue I observed that latest version of JHipster API(Jhipster 5.8.1) has been changed and it is not compatible with our generator. Please use JHipster version <= 5.8.0 until the fix.

**Comment by sudheerj** [comment] 2019-02-03 04:16
**Update**:  It is an issue from Core JHipster changes. As per the team, there will be a new patch release for the fix. Please use 5.8.0 release until it get released.

**Comment by bdevido** [comment] 2019-02-05 08:01
Same error with JHipster 5.7.1

node v8.11.3
yo v2.0.3
npm v6.5.0

```yo jhipster-primeng

WARNING! This method is deprecated. Use getAllJhipsterConfig

██████╗  ██████╗  ██╗ ███╗   ███╗ ███████╗ ███╗   ██╗  ██████╗
██╔══██╗ ██╔══██╗ ██║ ████╗ ████║ ██╔════╝ ████╗  ██║ ██╔════╝
██████╔╝ ██████╔╝ ██║ ██╔████╔██║ █████╗   ██╔██╗ ██║ ██║  ███╗
██╔═══╝  ██╔══██╗ ██║ ██║╚██╔╝██║ ██╔══╝   ██║╚██╗██║ ██║   ██║
██║      ██║  ██║ ██║ ██║ ╚═╝ ██║ ███████╗ ██║ ╚████║ ╚██████╔╝
╚═╝      ╚═╝  ╚═╝ ╚═╝ ╚═╝     ╚═╝ ╚══════╝ ╚═╝  ╚═══╝  ╚═════╝

Welcome to the JHipster primeng generator! v2.2.0

? Do you want to install PrimeNG? Yes
? Which theme would you like to use? Nova Light
? What is your preferred component selection criteria Component Groups
? Which component groups you would like to use? inputs
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'clientWebpack' of undefined
    at constructor.copyExternalAssetsInWebpack (/home/barbarad/.config/yarn/global/node_modules/generator-jhipster/generators/generator-base.js:671:24)
    at constructor.writing (/home/barbarad/.config/yarn/global/node_modules/generator-jhipster-primeng/generators/app/index.js:224:18)
    at Object.<anonymous> (/home/barbarad/.config/yarn/global/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:418:27)
    at /home/barbarad/.config/yarn/global/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/barbarad/.config/yarn/global/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/barbarad/.config/yarn/global/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:419:13)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by CurryWurry** [comment] 2019-02-06 08:01
can confirm: downgraded to Jhipster 5.8.0 and same error persists

**Comment by sudheerj** [comment] 2019-02-07 14:25
Here the problem is I can replicate the issue with 5.8.1 version and it is caused by JHipster issue fix https://github.com/jhipster/generator-jhipster/issues/9083. There will be a fix release from JHipster in few days. I will recheck it again here.

Let me try few more tests and I will try with jhipster-devbox as well.

**Comment by avdev4j** [comment] 2019-02-09 20:05
Hi !
I did the PR to extract the needle API. It was merged into 5.8.1 JHipster version.
So it doesn't affect version under it.

I'm surprised about this bug because the variable undefined is 'needleApi' which is used in the whole classe. I wonder where it can from.

I wonder if it can from the fact that we initialized the needleApi variable in the constructor.
Is it possible that JHipster-primeNG skip the baseGenerator constructor ?

`const JhipsterGenerator = generator.extend({});`
or
```
module.exports = JhipsterGenerator.extend({

    constructor: function (...args) { // eslint-disable-line object-shorthand
        generator.apply(this, args);

        this.option('default', {
            type: String,
            required: false,
            description: 'default option'
        });
}
```

If I can help.

**Comment by avdev4j** [comment] 2019-02-10 14:57
Ok I found the bug and suggest a fix here https://github.com/jhipster/generator-jhipster/pull/9233

**Comment by sudheerj** [comment] 2019-02-11 00:43
@avdev4j That's great. Thanks. I'm also trying from my end.

**Comment by sudheerj** [comment] 2019-02-14 01:40
@avdev4j I tried with your changes but it throws an error

![image](https://user-images.githubusercontent.com/3127317/52756515-948dc200-303c-11e9-84d6-368877c47b8b.png)

**Comment by avdev4j** [comment] 2019-02-14 07:57
I’ve made two changes:
- lazy load the needleApi variable (when you don’t inherit the base generator)
- fix the needleApi call on the addExternalResourceToRoot method

You should test from my branch (from my fork) and validate my PR on the main repository to be sure it will be included in next release.

I think you also fix it (dirty fix :)) in your module to fix it quickly and revert it on next JHipster release.

Tell me if you need more help

**Comment by sudheerj** [comment] 2019-02-19 15:42
I'am waiting for the fix from the team and latest release too.. I don't think it is a good idea to have dirty fix :)

**Comment by avdev4j** [comment] 2019-02-19 16:15
I’m agree. 

IMO my PR is ready to merge, I also added unit tests to prevent other regressions.

**Comment by sudheerj** [comment] 2019-02-21 15:23
Okay, thank you. The constructor function didn't fix the issue.

**Comment by avdev4j** [comment] 2019-02-21 17:08
What do you mean "The constructor function" ?

I've changed the way we initialize the needleApi in the generator base. 
```
    get needleApi() {
        if (this._needleApi === undefined || this._needleApi === null) {
            this._needleApi = new NeedleApi(this);
        }
        return this._needleApi;
    }
```

Instead of inject it into the constructor we now have a lazy loading. You still can use public API without extend the generator base.

My PR has been merged today so I advise you to test with the v5.X_maintenance branch.
clone generator-jhipster locally, switch to the v5 branch, do a `npm link` in the jhipster folder, do a `npm link generator-jhipster` into your project folder, run jhipster and add primeNG module.

**Comment by avdev4j** [comment] 2019-02-21 17:28
I've juste made a test successfully.

clone jhipster, switch to v5 branch, do `npm install`, do `npm link`
clone primeNG module, do `npm install`, do `npm link generator-jhipster` then `npm link`

Create a new project in /tmp/test_primeNG_v5x
run `jhipster`
run `yo jhipster-primeng`

it works !

It's not really easy to test with npm link 'cause sometimes the behaviour is not very clear.

<img width="813" alt="capture d ecran 2019-02-21 a 18 27 35" src="https://user-images.githubusercontent.com/37835668/53188812-68f37480-3606-11e9-83cb-ca4455db7d78.png">

**Comment by sudheerj** [comment] 2019-02-24 06:28
Thanks for testing. Now I'am waiting for the new release from JHipster.

**Comment by edillmann** [comment] 2019-02-28 09:05
Hi, this bug is a real blocker, i tried with jhipster 5.7.0 and got the same problem

TypeError: Cannot read property 'clientWebpack' of undefine

is there an estimate date where this will be corrected as I really would like to use this generator :-)

regards,

**Comment by sudheerj** [comment] 2019-02-28 15:34
@edillmann We contacted JHipster team to make it ASAP in different channels. As per them, there will be a new release.

**Comment by avdev4j** [comment] 2019-02-28 17:38
JHipster 5.8.2 is available !

**Comment by edillmann** [comment] 2019-03-01 10:28
@sudheerj thx for you return

**Comment by sudheerj** [comment] 2019-03-02 05:32
@avdev4j  I tried with 5.8.2 release and latest commits of JHipster-PrimeNG module. But still I can see the same error.

**Comment by sudheerj** [comment] 2019-03-02 09:36
@avdev4j Just an update that the issue is resolved. Earlier it has older JHipster version.

**Closed** 2019-03-02 09:36 UTC
