### ISSUE TITLE
webpack: Failed to compile (Jhipster 4.14.0)

### ISSUE THREAD

**Issue by tchronis** [sudheerj/generator-jhipster-primeng#36] opened 2018-03-06 14:55 UTC
Hello sudheerj ,

I tried to add primeng in my jhipster app following exactly the readme file (both with yarn and npm) but I could not get the success page :-(

I added `@angular/http` to package.json that was missing. 

i18 and SASS are on. Angular 5.

So I get this error below - any hint?

`ERROR in ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./src/main/webapp/content/scss/vendor.scss
Module not found: Error: Can't resolve 'primeng-extensions/resources/primeng-extensions.min.css' in '/home/tchr/Projects/tagv/atlas/src/main/webapp/content/scss'
 @ ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./src/main/webapp/content/scss/vendor.scss 4:10-126
 @ ./src/main/webapp/content/scss/vendor.scss
 @ ./src/main/webapp/app/vendor.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts
 @ multi (webpack)-dev-server/client?http://localhost:9060 webpack/hot/dev-server ./src/main/webapp/app/app.main
`

Thank you,

Theodore

**Comment by sudheerj** [comment] 2018-03-12 00:45
The issue is fixed with latest version. If still it creates an issue then please comment here.

**Closed by sudheerj** 2018-03-12 00:45 UTC

**Comment by tchronis** [comment] 2018-03-12 11:55
It worked. I had again to add @angular/http manually.

Warnings on spaces, empty lines etc are pasted here: https://pastebin.com/hp7fH43N

Thank you.

**Comment by sudheerj** [comment] 2018-03-19 15:55
Fixed TSLint issues.Thanks
