### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: StaticInjectorError[ViewContainerRef]:

### ISSUE THREAD

**Issue by cospuiu** [sudheerj/generator-jhipster-primeng#26] opened 2017-12-21 22:42 UTC
Hello sufheerj, 
There is a issue, we got a white page. 
I think the problem is because Angular 5 use HttpClientModule instead of HttpModule and HttpClient instead of Http.

A screenshot: 
![image](https://user-images.githubusercontent.com/29779367/34278004-6f221b58-e6a8-11e7-8392-e66493dc28c7.png)

Any tips?

thank you

**Comment by sudheerj** [comment] 2017-12-22 00:54
Do you got this issue for specific components. Last time I tried few components without an issue.

**Comment by sudheerj** [comment] 2017-12-22 02:36
This is not an issue with HTTP or HTTP module. It is about injecting ViewContainerRef with in services https://stackoverflow.com/questions/41278179/anguler2-unhandled-promise-rejection-no-provider-for-viewcontainerref-in-d

**Comment by GuillaumeFAVRE73** [comment] 2017-12-26 23:27
I have the same error with latest jHipster version 4.13.0. Basic install and then, directly PrimeNG installation, with all components. I get same error.

**Comment by cospuiu** [comment] 2017-12-27 11:44
Hello sudheerj, as GuiF007, i still have the same issue. 
Thank you.

**Comment by sudheerj** [comment] 2017-12-29 12:40
I can able to replicate the issue with latest Angular5 migration. There is no change even after converting to HTTPClient.

**Comment by sudheerj** [comment] 2017-12-31 08:52
The issue is caused by primeng-extensions library. I'am trying to find the further rootcause of this issue.

**Comment by cospuiu** [comment] 2018-01-02 14:58
hi sudheerj, 
i just created a new jhipster project, with primeng and primeng-extensions. now i have a white page.
A screenshoot:

![image](https://user-images.githubusercontent.com/29779367/34487693-bf8970b0-efd5-11e7-9e60-f5fbbc99ba18.png)

thank you.

**Comment by sudheerj** [comment] 2018-01-02 19:11
The issue is occurred by wizard module of PrimeNG- extensions during Angular 5 upgrade. Please remove wizard module until it get fixed.Thanks.

**Comment by GuiF007** [comment] 2018-01-05 08:30
What's the purpose of this module ?

I had the idea to delete it before you wrote this message, and it works better now. But some pages seems to be not really dynamic...

**Comment by sudheerj** [comment] 2018-01-05 10:15
This module is used to navigate between features of each component. If you remove this component then all features fall on the same page.

**Comment by sudheerj** [comment] 2018-01-08 15:58
Issue is fixed in 2.0.19 release. Due to duplicate Angular dependencies then it is not able to resolve the providers. Thanks for reporting.

**Closed by sudheerj** 2018-01-08 15:58 UTC
